// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	Hash    string
	Meta    string
	MetaKey string
}{
	Hash:    "hash",
	Meta:    "meta",
	MetaKey: "meta_key",
}
